### ISSUE TITLE
Sql4Cds engine : RetrieveEntityRequest is not yet supported.

### ISSUE THREAD

**Issue by sybaris** [DynamicsValue/fake-xrm-easy#106]
Hi,

I try to use FakeXrmEasy with Sql4Cds engine to test my Sql Queries.

I have the following exception : 
FakeXrmEasy.Abstractions.Exceptions.OpenSourceUnsupportedException: 'Exception occurred: The organization request type 'Microsoft.Xrm.Sdk.Messages.RetrieveEntityRequest' is not yet supported... . If you are using FakeXrmEasy in an Open Source project please raise an issue via our GitHub issue tracker at https://github.com/DynamicsValue/fake-xrm-easy. Also please do consider giving back to the OSS community by contributing back to our project via a pull request. The community will appreciate any kind contribution even if small: typos, comments, steps to reproduce a bug, documentation, or new ideas for new features. If you are unsure about our licensing, please have a look at our licensing FAQ here: https://dynamicsvalue.github.io/fake-xrm-easy-docs/licensing/faq/'

Regards
Sybaris

https://github.com/MarkMpn/Sql4Cds/issues/318

**Comment by sybaris** [comment]
Hi

Thanks for your answer.
I have added these 2 lines in my MiddlewareBuilder :
`.AddFakeMessageExecutors(Assembly.GetAssembly(typeof(RetrieveVersionRequestExecutor)))                        .AddGenericFakeMessageExecutors(Assembly.GetAssembly(typeof(NavigateToNextEntityOrganizationRequestExecutor)))
`
Now I have another error whn trying to connect using Sql4CdsConnection :
`'Entity 'sdkmessagerequest' is not found in the metadata cache'`

Any idea why we have this ?

Regards
Sybaris

**Comment by sybaris** [comment]
Hi

Here the test method to reproduce :
```
        [TestMethod]
        public void TestMethod1()
        {
            var context = MiddlewareBuilder
                        .New()
                        .AddCrud()
                        .AddFakeMessageExecutors()
                        .AddFakeMessageExecutors(Assembly.GetAssembly(typeof(RetrieveVersionRequestExecutor)))
                        .AddGenericFakeMessageExecutors(Assembly.GetAssembly(typeof(NavigateToNextEntityOrganizationRequestExecutor)))
                        .UseCrud()
                        .UseMessages()
                        .SetLicense(FakeXrmEasyLicense.RPL_1_5)
                        .Build();

            var service = context.GetOrganizationService();

            var organization = new Entity("organization");
            organization.Id = Guid.NewGuid();
            organization["name"] = "UnitTestOrganization";
            context.Initialize(organization);

            var connection = new Sql4CdsConnection(service);
        }
```
I use mstest 4.6.2
And these packages nuget :
```
  <package id="FakeXrmEasy.Abstractions.v9" version="2.3.0" targetFramework="net462" />
  <package id="FakeXrmEasy.Core.v9" version="2.3.0" targetFramework="net462" />
  <package id="FakeXrmEasy.Messages.v9" version="2.3.0" targetFramework="net462" />
  <package id="MarkMpn.Sql4Cds.Engine" version="7.3.0" targetFramework="net462" />
```

![image](https://github.com/DynamicsValue/fake-xrm-easy/assets/11009997/4dddd4d7-af41-49c9-a79e-09c2bc5a5b46)

I hope you will be able to reproduce and understand what happens...
Regards
Sybaris

**Comment by sybaris** [comment]
Hi,

Any news about my last post with an example to reproduce ?

Regards
Sybaris

**Comment by jordimontana82** [comment]
Thanks @sybaris for the info.

I was indeed able to reproduce . That message is an expected error message that happens when you try to query an entity record that doesn't exist and you're using late bound entity records.

![image](https://github.com/DynamicsValue/fake-xrm-easy/assets/3968950/4300534d-7f51-4f75-80d2-c6a7c2491b69)

In this case, Sql4CdsConnection constructor is trying to query "sdkmessagerequest" records which is triggered via a MetadataCache class in Sql4Cds's engine library.  However no records of that type were provided in the .Initialize() call hence the error. 

If you provide some test data via .Initialize() before calling such constructor (i.e. sdkmessagerequest) records then it should work.

I'd suggest following it from there (looking at Mark's Sql4Cds source code) to see what other records might be needed but my understanding is that not an issue with FakeXrmEasy. https://github.com/MarkMpn/Sql4Cds/blob/5819139ad96dfa34007c3fcce6f87ac0100068d2/MarkMpn.Sql4Cds.Engine/MessageCache.cs#L60


I've seen you raised another issue at that repo that was closed, I'll add a few comments in there as well.

https://github.com/MarkMpn/Sql4Cds/issues/318
