### ISSUE TITLE
WhoAmIRequest improvements

### ISSUE THREAD

**Issue by jordimontana82** [DynamicsValue/fake-xrm-easy#23]
https://github.com/jordimontana82/fake-xrm-easy/pull/438

**Comment by bwmodular** [comment]
Does the existence of this issue mean that this addition from v1 (https://github.com/jordimontana82/fake-xrm-easy/pull/438) has not yet made it into v2/v3?
Just migrating a project from v1 to v2 which has some tests which work with Calendar rules and they have stopped working. I think it's because the organisation of the user is no longer returned in the WhoAmIResponse...
Not a problem, just checking I don't need to do anything different to get it to work...

**Comment by bwmodular** [comment]
Just taken a look through the original PR - I'll have a go at making the same changes to v2/3 - I'll let you know if I hit any problems....
