### ISSUE TITLE
Automatic Registration in Pipeline Simulation expects SdkMessage, SdkMessageFilter, SdkMessageProcessingStep and PluginType when using early bound entities

### ISSUE THREAD

**Issue by jordimontana82** [DynamicsValue/fake-xrm-easy#95]
Check if using early bound and if all of the above entities were generated along with other entities. If not, raise a dedicated exception as the current message is a bit broad and not specific: "Could not find reflected type for sdkmessage".

**Comment by jordimontana82** [comment]
Great feedback @teppolainio  !

I think we could also ship pre-generated early bound classes for these types SdkMessage, SdkMessageFilter, and so on, and automatically resolve them if not found in an assembly that was explicitly generated. 

How does that sound?

**Comment by jordimontana82** [comment]
Hypothesis, this might also happen if RegisterPluginStep is called after .Initialize or any other method that sets an Assembly with early bound types for the first time.

**Comment by teppolainio** [comment]
@jordimontana82 I tested your hypothesesis and it seems to hold true.

It would be great if one wouldn't have to add early bound classes for boilerplate entities just for the sake of mockup library. Coud you for example ship some sort of metadata factory which could create necessary metadata for entities sdkmessage, sdkmessagefilter, sdkmessageprocessingstep and plugintype when these aren't included into those entities necessary for plugins application logic to run? Then you could hint on exception message something like "Metadata for entities these-and-these is required when using early bound classes. Either add these to your generated early-bound classes or add necessary metadata to FakeXrmEasy using ThisAwesomeMetadataFactory.CreateSomeBoilerplateEntityMetadata()" etc.

**Original run**
On test base class constructor:
`context.EnableProxyTypes(typeof(VeryInterestingPlugin).Assembly);`

On test method on separate test class:
`context.Initialize(IEnumerable<Entity> entities)`
`var step = new PluginStepDefinition() { ... }`
`context.RegisterPluginStep<VeryInterestingPlugin>(step);`
-->
Test run fails with `System.Exception : Couldnt find reflected type for sdkmessage`.

**Modified run number one**
On test base class constructor:
`context.EnableProxyTypes(typeof(VeryInterestingPlugin).Assembly);`

On test method on separate test class:
`var step = new PluginStepDefinition() { ... }`
`context.RegisterPluginStep<VeryInterestingPlugin>(step);`
`context.Initialize(IEnumerable<Entity> entities)`
-->
Test run fails with `System.Exception : Couldnt find reflected type for sdkmessage`.

**Modified run number two**
On test base class constructor:
`// context.EnableProxyTypes(typeof(VeryInterestingPlugin).Assembly);`

On test method on separate test class:
`var step = new PluginStepDefinition() { ... }`
`context.RegisterPluginStep<VeryInterestingPlugin>(step);`
`context.Initialize(IEnumerable<Entity> entities)`
-->
Test succeeds (or actually failes due to NotImplementedException from plugin class i.e. just like it should).

**Comment by jordimontana82** [comment]
I like that idea @teppolainio

**Comment by jordimontana82** [comment]
@teppolainio  This made it to this version: https://www.nuget.org/packages/FakeXrmEasy.Plugins.v9/2.3.2#release-body-tab

Slightly different approach in the end, it'll check if using early bound, and if so, search for all the needed types.

If all of them are present in the user-defined assembly, it'll use those.
If none of them are present, it'll include them automatically.
If some of them are present but not all, will raise an exception to make it clearer.

Should cover all possible scenarios.
